name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        php: ['8.3', '8.4']
        dependency-version: [prefer-lowest, prefer-stable]

    name: Tests P${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Aspell (Ubuntu, macOS, Windows)
      shell: bash
      run: |
        if [[ "$RUNNER_OS" == "Linux" ]]; then
          sudo apt-get update && sudo apt-get install -y aspell aspell-en
        elif [[ "$RUNNER_OS" == "macOS" ]]; then
          brew install aspell
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          powershell.exe 'curl http://ftp.gnu.org/gnu/aspell/w32/Aspell-0-50-3-3-Setup.exe -o aspell-installer.exe;
            curl http://ftp.gnu.org/gnu/aspell/w32/Aspell-en-0.50-2-3.exe -o aspell-en-dict.exe;
            Start-Process -Wait -FilePath .\aspell-installer.exe -Argument "/silent" -PassThru;
            Start-Process -Wait -FilePath .\aspell-en-dict.exe -Argument "/silent" -PassThru;
            $currentPath = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::User);
            [Environment]::SetEnvironmentVariable("Path", $currentPath + ";C:\Program Files (x86)\Aspell\bin", [EnvironmentVariableTarget]::User);'
        fi

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: dom, mbstring, zip
        coverage: none

    - name: Get Composer cache directory
      id: composer-cache
      shell: bash
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: dependencies-php-${{ matrix.php }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-${{ hashFiles('composer.json') }}
        restore-keys: dependencies-php-${{ matrix.php }}-os-${{ matrix.os }}-version-${{ matrix.dependency-version }}-composer-

    - name: Install Composer dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --prefer-dist

    - name: Integration Tests
      run: php ./vendor/bin/pest
